- name: Perform backup
  shell: "./setup.sh -b"
  args:
    chdir: "{{ ansibletower.root }}/ansible-tower-setup-{{ ansibletower.version }}"

- name: Upload backup to S3
  s3:
    bucket: "{{ ansibletower.backup_bucket }}"
    object: tower-backup-latest.tar.gz
    src: "{{ ansibletower.root }}/ansible-tower-setup-{{ ansibletower.version }}/tower-backup-latest.tar.gz"
    mode: put
