- name: Configure credentials
  template:
    src: inventory.j2
    dest: "{{ ansibletower.root }}/ansible-tower-setup-{{ ansibletower.version }}/inventory"
  no_log: "{{ ansibletower.no_log }}"

- name: Execute upgrade/installation
  become: yes
  shell: "./setup.sh"
  args:
    chdir: "{{ ansibletower.root }}/ansible-tower-setup-{{ ansibletower.version }}"
  async: 7200
  poll: 5

