---
- debug: var=ansibletower verbosity=1
  tags: vars

- block:
    - name: Include action tasks
      include: "{{ ansibletower.action }}.yml"
  rescue:
    - debug: msg='Action invalid. Use install, upgrade, backup or restore'  
